### ISSUE TITLE
你好 ，很不错，很棒

### ISSUE THREAD

**Issue by wy19901227** [CoderJackyHuang/HYBMasonryAutoCellHeight#1]
本我我也是喜欢用代码的，这个自动计算我是我想干的事，无奈看不懂masonry内部的逻辑，runtime也不行，我真的不懂，你是怎么发现指定cell中最后一个试图就可以计算高度了 呢？打死我，我也想不到，我的想法是masonry其实是基于apple的autolayout，然后布局完成以后，应该可以通过contentView systemLayoutSizeFittingSize:UILayoutFittingCompressedSize 来计算得到，但是事实  算不出高度，有点纳闷，难道说masonry布局以后，cell并没有添加约束吗?应该 都添加了把。

还有个就是 ios8 以后，tableview的cell高度不在缓存，每次滑动都会重新计算，所以希望还是做个缓存高度的机制吧。

**Comment by CoderJackyHuang** [comment]
我在公司使用的版本是使用缓存的，但是有的时候缓存会出问题，比如不同的cell复合问题，因为缓存可能会出现直接获取缓存的高度，而导致所得高度不正确。如果有必要，我可以追加缓存机制
