### ISSUE TITLE
大屏手机上layoutIfNeeded好像还是按照320的宽度布局

### ISSUE THREAD

**Issue by liyouleo911** [CoderJackyHuang/HYBMasonryAutoCellHeight#2]
大屏手机上layoutIfNeeded好像还是按照320的宽度布局，这样高度似乎算出来跟实际的对不上？

**Comment by CoderJackyHuang** [comment]
我不清楚你是怎么使用的。我们好多个项目在使用，适配6.0及其以上版本，都没有出现你说的问题。


原始邮件
发件人:Leonotifications@github.com
收件人:CoderJackyHuang/HYBMasonryAutoCellHeightHYBMasonryAutoCellHeight@noreply.github.com
发送时间:2015年10月20日(周二) 11:31
主题:[HYBMasonryAutoCellHeight] 大屏手机上layoutIfNeeded好像还是按照320的宽度布局 (#2)


大屏手机上layoutIfNeeded好像还是按照320的宽度布局，这样高度似乎算出来跟实际的对不上？

**Comment by liyouleo911** [comment]
我分别在5s和6plus的模拟器上跑了你的demo，5s上last cell距离底部的高度是正确的，6 plus上很明显能看出两个last cell距离底部的高度不同且均大于5s上面的距离。我猜测有可能它layoutIfNeeded还是使用320的宽度去排列文字，这样在6 plus上算出来的label高度其实太高了，不知道是不是这个原因？我用的xCode Version 7.0 (7A220)，系统是10.10.5 (14F27)。

![simulator screen shot 2015 10 21 3 33 31](https://cloud.githubusercontent.com/assets/1015944/10630573/0fa6a11c-780a-11e5-93a3-21111512657f.png)

![simulator screen shot 2015 10 21 3 37 48](https://cloud.githubusercontent.com/assets/1015944/10630572/0fa2464e-780a-11e5-9edc-0e56e8ddd673.png)

**Comment by CoderJackyHuang** [comment]
你的猜想不正确。不是因为还使用320的宽度，那是不可能的。问题出在6s/6plus上添加了约束后不能调用sizeToFit，不然会出现计算不准确的问题。
