### ISSUE TITLE
demo运行出现高度问题

### ISSUE THREAD

**Issue by janicezhw** [CoderJackyHuang/HYBMasonryAutoCellHeight#3]
![f7793848-24c3-4c6e-99b9-9d6bd69ec630](https://cloud.githubusercontent.com/assets/5327563/12087234/6b441a4e-b30c-11e5-88db-4e25451689cf.png)

运行demo 出现lastview 距离cell底部 高度不一致的情况。。。 

iPhone6s 9.2 模拟器

（图片发不上来。。）

**Comment by CoderJackyHuang** [comment]
感谢您的反馈，代码已经提交，请更新代码！


原始邮件
发件人:janicezhwnotifications@github.com
收件人:CoderJackyHuang/HYBMasonryAutoCellHeightHYBMasonryAutoCellHeight@noreply.github.com
发送时间:2016年1月4日(周一) 17:56
主题:[HYBMasonryAutoCellHeight] demo运行出现高度问题 (#3)


运行demo 出现lastview 距离cell底部 高度不一致的情况。。。
iPhone6s 92 模拟器
（图片发不上来。。）

**Comment by CoderJackyHuang** [comment]
问题出在调用了sizeToFit。不知道为什么在6s上使用约束与sizeToFit有什么冲突
