### ISSUE TITLE
行高计算不准的bug

### ISSUE THREAD

**Issue by wxh794708907** [CoderJackyHuang/HYBMasonryAutoCellHeight#6]
有一个bug，在我项目中我使用了你的这个库，发现自动计算行高的时候，在文本特别多的时候，iPhone6s以上都计算的不对，cell与cell之间会有空隙，iPhone5s好像没事

**Comment by CoderJackyHuang** [comment]
使用prefer..width指定宽才可以精准！这跟这个库没有关系
